### ISSUE TITLE
Midterm feedback

### ISSUE THREAD

**Issue by philsinatra** [gnt36/idm221-gnt36#1]
## HTML validation

The [line break](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br) element is a self-closing element. You don't need to [program a closing tag](https://github.com/gnt36/idm221-gnt36/blob/65312ab0747e7417231b9604d0a7358b61d98a29/index.html#L30) when using this element.

```diff
- <h1 class="special">Lou Tranchitella, <br>Digital Artist.</br></h1>
+ <h1 class="special">Lou Tranchitella, <br>Digital Artist.</h1>
```

Check all of your HTML pages with the [HTML validation service](https://validator.w3.org/#validate_by_input)

## Repository content

Your images are not included in your repository, so I cannot check anything related to your images' presentation or file size.

## Expand your CSS

- Style your navigation to be touch friendly on small screens. Look online for [guidelines](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/buttons/#best-practices) and recommendations for sizing and position.
- Finalize your typography and make it consistent. Your homepage uses Bubblegum Sans for the main heading, but the other pages use Altone Trial. Review your paragraph text on your phone and in browser emulators. You can probably increase the font size a bit, and you need to increase the line height once you finalize the size. Remember the order of decisions we discussed in class: select the family, determine the size scale, address line height, and all the other properties.

## Get creative

The content on your work page is seventeen images stacked on top of each other. Can you think of any ways to present the content more creatively? Look around online for inspiration. At a minimum, can you enhance the markup to include captions or descriptive text? Do you have enough content to make a stand-alone page for each image with more information about image/project? It's hard for me to elaborate more specifically without seeing the images.

## Trim the fat

Do you need a contact page? Your footer includes social media links that will be available on every page. What will be different on the contact page? 

## DRY

Don't repeat yourself. Remember how CSS cascades. If you set the foreground color on the `body` element, every element will use that color. You only need to redefine a foreground color if you want to change it for a particular element.

```css
body nav {
    background-color: #CF690A;
    color: #131313;
    font-style: var(--font--sans-serif);
    font-weight: 400;
    font-family: 'AltoneTrial_Regular';
    line-height: normal;
    letter-spacing: normal;
}

main div h1 {
    color: #131313;
    font-style: var(--font--sans-serif-bold);
    font-weight: 700;
    font-family: 'AltoneTrial_Bold';
    line-height: normal;
    letter-spacing: normal;
}

main div h2, h3, h4, h5, h6 {
    color: #131313;
    font-style: var(--font--sans-serif);
    font-weight: 400;
    font-family: 'Questrial_Regular';
    line-height: normal;
    letter-spacing: normal;
}

main div p {
    color: #131313;
    font-style: var(--font--sans-serif);
    font-weight: 400;
    font-family: 'Questrial_Regular';
    line-height: normal;
    letter-spacing: normal;
}
```

Simplify everything.

```diff
body {
  /* you defined a custom property, why not use it? */
+ color: var(--color-dark); 

  /* everything will use this font unless you change it */
  /* note: you want 'font-family', not 'font-style' */
+ font-family: var(--font--sans-serif); 
}

body nav {
  background-color: #CF690A;
- color: #131313;
- font-style: var(--font--sans-serif);

/* ❔ 400 is typically the default, you may not have to declare it */
- font-weight: 400; 

/* I don't see a font-face declaration for this family */
  font-family: 'AltoneTrial_Regular'; 

  /* default value */
- line-height: normal; 

  /* default value */
- letter-spacing: normal; 
}

main div h1 {
- color: #131313;
- font-style: var(--font--sans-serif-bold);
  font-weight: 700;
  font-family: 'AltoneTrial_Bold';
- line-height: normal;
- letter-spacing: normal;
}

main div h2, h3, h4, h5, h6 {
- color: #131313;
- font-style: var(--font--sans-serif);
- font-weight: 400;
  font-family: 'Questrial_Regular';
- line-height: normal;
- letter-spacing: normal;
}

main div p {
- color: #131313;
- font-style: var(--font--sans-serif);
- font-weight: 400;
  font-family: 'Questrial_Regular';
- line-height: normal;
- letter-spacing: normal;
}
```

If you want to specifically select heading elements inside divs in the main, you have to be more specific with your selector

```diff
- main div h2, h3, h4, h5, h6 {
+ main div h2, div h3, div h4, div h5, div h6 {
```

If these end up sharing the same styles, you can add the paragraph to your selector

```css
main div h2, div h3, div h4, div h5, div h6, div p {
```

If you're going to set a different font for all of these elements, should the primary body copy font change instead?

```diff
html {
- --font--sans-serif: 'AltoneTrial_Regular', Arial, sans-serif;
+ --font--sans-serif: 'Questrial_Regular', Arial, sans-serif;
}
```

If you set the primary font and use it on the `body`, you only have to redeclare `font-family` for elements not using the primary.
